# Github action to build and verify the fortran packages
#

name: Fortran Package Verification

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v4
      
      - uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: 'v0.10.1'
          github-token: ${{ secrets.GITHUB_TOKEN }}     

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install python libraries
        run: pip3 install --user -r backend/requirements.txt

      - name: temporary folder for fortran packages
        run: cd backend/static && mkdir temp

      - name: load env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > backend/.env
          
      - name: validate fortran packages
        run: cd backend && python validate.py
