name: Run Tests for Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
    MONGO_DB_NAME: testregistry
    MONGO_URI: mongodb://localhost:27017/
    MONGO_USER_NAME: Admin
    MONGO_PASSWORD: Admin
    SALT: MYSALT
    HOST: localhost
    RESET_EMAIL: reset@localhost.com
    RESET_PASSWORD: reset
    SUDO_PASSWORD: fortran
    IS_CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout page source
        uses: actions/checkout@v4

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-port: 27017  
          
      - name: Setup Python
        uses: actions/setup-python@v5
  
      - name: Install python libraries
        run: pip3 install --user -r backend/requirements.txt

      - name: run tests
        run: cd backend && python -m unittest discover -s tests